[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E", "F", "W", "I", "B"]
exclude = ["venv", ".venv", "node_modules", "templates", "static"]

[tool.ruff.lint.isort]
known-first-party = ["utils"]